[phases.setup]
nixPkgs = ["python311", "gcc"]

[phases.install]
cmds = [
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[start]
cmd = "cd telebot && python bot_logger.py & cd root && python main.py"
